# Generated by Django 4.2.3 on 2023-07-05 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-performance", "created")},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="marks",
            new_name="performance",
        ),
    ]
